version: '2'

networks:
    LEMP:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: LEMP_nginx
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - LEMP

    mariaDB:
        image: mariadb:latest
        container_name: LEMP_mariaDB
        volumes:
            - ./database:/var/lib/mysql:rw
        ports:
            - "3306:3306"
        depends_on:
            - nginx
        environment:
            - MYSQL_ROOT_PASSWORD=654321          
        networks:
            - LEMP    

    php:
        image: php:7-fpm-alpine
        container_name: LEMP_php
        volumes:
            - ./code:/code
        ports:
            - "9000:9000"       
        networks:
            - LEMP

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: LEMP_phpMyAdmin
        ports:
            - "8183:80"
        environment:        
            PMA_ARBITRARY: 1
        depends_on:
            - mariaDB
        networks:
            - LEMP
    



